export const docSpec = [
    'Psychiatry',
    'Urology',
    'Plastic Surgery',
    'Orthopedics',
    'Obstetrics and Gynaecology',
    'General Surgery',
    'Surgical Gastroenterology',
    'Cardio-thoracic surgery',
    'Neurosurgery',
    'Neurology',
    'General Medicine',
    'ENT (Ear, Nose and Throat)',
    'Medical Gastroenterology',
    'Conito-urinary surgery',
    'Oncology (Cancer Care)',
    'Anesthesiology',
    'Dermatology',
    'Ophthalmology',
    'Endocrinology and Clinical Hematology',
    'Pediatrics',
    'Pediatric Surgery'
]
